### ISSUE TITLE
Where does the DisplayPort connector lead?

### ISSUE THREAD

**Issue by Dakkaron** [FrameworkComputer/ExpansionBay#4]
Does it go to the internal display (thus bypassing the need to route the video signal over PCIE), to the IO (to attach external displays) or somehow to the CPU/integrated GPU?

Or is it the output coming from the iGPU?

What can it be used for?

**Comment by jyancat** [comment]
Display IN, I don't know how it is electrically connected but I'd assume it would be close to directly connected with the exception of some kind of mux to switch between the iGPU and the expansion bay connector. Useful for a GPU expansion bay module or even use your FW16 as a portable monitor.

**Comment by Dakkaron** [comment]
That's really cool, thanks!

**Comment by jyancat** [comment]
I'd suggest you mark this as closed.
